### ISSUE TITLE
Tag Manager startup issue - not available as plugin in the Marketplace

### ISSUE THREAD

**Issue by b-pfl** [matomo-org/tag-manager#147]
Dear all, 

on my Matomo installation, I have issues, getting to run the Tag Manager. I was able to activate it but then the page for creating a new container was empty. Since the manager is a plugin, my idea was to reinstall it and see if that fixes my problem. Thus, I removed it and then had to find out that it is not available in the Market place - is that intended? 
What should I do to get it up and running again...?

**Comment by tsteur** [comment]
Hi there, the plugin is now bundled with Matomo 3.7.0+.

The creating container issue was empty was a caching issue which will be fixed in 3.8.0 which will be released soon. 
See https://github.com/matomo-org/tag-manager/issues/132 and https://github.com/matomo-org/tag-manager/issues/140

Try to delete your cache by either emptying the `tmp` directory in your Matomo directory or executing `./console cache:clear` within your Matomo directory if you can execute commands.

To get it again, please update to the latest Matomo version. If you are already on Matomo 3.7.0, follow the 3-step manual update https://matomo.org/docs/update/#the-manual-three-step-update or wait until Matomo 3.8.0 is released in couple days.

Cheers
