### ISSUE TITLE
How do I update a tag parameter?

### ISSUE THREAD

**Issue by lockland** [matomo-org/tag-manager#183]
I've created a custom tag with a lot of parameters and then, on a new version of that, I've changed some parameters name and its values and deployed that plugin on matomo. The new tags works properly but the old ones broke whereas the parameters had changed.

So I wanna know if there is a documentation or a way to update those parameters without access the database and updating the parameters there. #

**Comment by tsteur** [comment]
Hi @lockland this sounds like a question for our forum: https://forum.matomo.org

You might want to provide a bit more details since it's not quite clear what you are after.

In general you don't need to make change on the DB though, there is an API that let's you make changes and maybe that's something for you: https://developer.matomo.org/api-reference/reporting-api#TagManager

**Comment by lockland** [comment]
Thank you for your reply @tsteur and sorry about don't be clear enought.

I was just talking about create a plugin migration like describe here: https://developer.matomo.org/api-reference/Piwik/Updates
