### ISSUE TITLE
Variables not showing up within the UI when using the API

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#237]
Hi there,
I am importing variables through the API within Matomo Tag Manager.
Here is my request:
curl "http://localhost/mat311/matomo/index.php" -G -d "module=API&method=TagManager.addContainerVariable&idSite=7&token_auth=ed6fb0020d5758e5e94aef3a7f37bb5f&idContainer=UXu2xVDF&idContainerVersion=74&type=DataLayer&parameters[dataLayerName]=testou&name=1840"
When I export the json file of the container, I can clearly see the variable in the json.
Though it is not appearing at all within the UI.

**Comment by tsteur** [comment]
Is the ID of the container version 100% correct? The UI uses the same method so it generally seems to work. Maybe you can confirm this by adding a data layer variable through the API. This would than indicate it seems of an issue around sending correct variables etc rather than a bug (where technically https://forum.matomo.org/ would be a better place to discuss).

This is how the request looks like from the UI:
![image](https://user-images.githubusercontent.com/273120/79160318-b09e1680-7e2d-11ea-954b-d3b97939d26b.png)

I don't know what the -G -d parameters do but might be good to double check.

**Comment by Chardonneaur** [comment]
Hi Thomas,
Thank you so much for your help.
It was indeed my fault.
Here is what the documentation of the API is saying "The current version that a user is editing is called the "draft" version. You can get the ID of the "draft" version by calling {@link TagManager.getContainer}." so one need to call "TagManager.getContainer", then need to look through the result and look for the draft tag, then it can get the right "idContainerVersion".
Thanks,

**Comment by tsteur** [comment]
Glad it works now @Chardonneaur
