### ISSUE TITLE
Matomo Configuration: Using variable in Matomo URL results in validation error

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#248]
![trackingdomain-variable](https://user-images.githubusercontent.com/1018973/83959036-3ad88900-a879-11ea-805a-5948dc5b9539.JPG)

**Comment by tsteur** [comment]
Thanks @peterbo I can see in https://github.com/matomo-org/tag-manager/blob/3.x-dev/Template/Variable/MatomoConfigurationVariable.php#L59 it's only validating for URL but should be more like the idSite check https://github.com/matomo-org/tag-manager/blob/3.x-dev/Template/Variable/MatomoConfigurationVariable.php#L74-L86 . I'm actually now thinking it should probably only validate for not empty since the value could be eg `https://{{foo}}/matomo...`. I suppose removing the url like validator would fix that issue.

**Comment by peterbo** [comment]
Hi @tsteur - I removed the URL validator for some instances yesterday and it works perfectly. Yes, this would definitely make sense to a) remove the URL validation completely or b) if "{{" is in string, then only validate NotEmpty, if not, validate also for URL.

**Comment by tsteur** [comment]
👍  created https://github.com/matomo-org/tag-manager/pull/250
