### ISSUE TITLE
When using _paq.push(['trackPageView']); in a Custom HTML tag (with bundled and default tracker in configuration), no tracking request is fired

### ISSUE THREAD

**Issue by peterbo** [matomo-org/tag-manager#282]
When no "Matomo Analytics" prepared pageView tag is fired, the _paq.push call will not trigger a pageView request and _paq stays an array. The tracker object doesn't seem to be initialised without firing a "Matomo Analytics" prepared pageView tag.

**Comment by tsteur** [comment]
Hi @peterbo the Matomo tracker only gets initialised once the Matomo Tag fires meaning on an event, page view or goal. I would say this is currently expected because we wouldn't maybe 100% correctly know when to initialise the tracker. Like we might not be able to initialise the Matomo tag on "pageview" or when the script is loaded directly because the dataLayer etc might not be prepared yet etc. So far the only workaround I could think of be to have another option "initialise" or something similar next to `pageview|event|...` which would then only initialise the tracker. Would that maybe help?

**Comment by peterbo** [comment]
Hey @tsteur! Thanks for your fast response! I think this might help. I don't have the architecture of the Container in mind, but would it make sense to initialise _paq directly after loading the configuration that bundles / sets the default tracker, independently of the fact that a pageView/Event/Goal tag is being attached? Or might this introduce more problems?

This feature might come in handy in cases, where the implementation is highly customized. In this individual case, I would need to fire the PageView tag as Custom Html to have better control over the Custom Dimensions (because subsequent events are also fired via custom HTML and may not reuse custom dimensions from the tracker configuration). So the ladder is basically the culprit in this case.

**Comment by tsteur** [comment]
@peterbo could you try https://github.com/matomo-org/tag-manager/pull/283 ? It might be as simple as that.

> I don't have the architecture of the Container in mind, but would it make sense to initialise _paq directly after loading the configuration that bundles / sets the default tracker, independently of the fact that a pageView/Event/Goal tag is being attached? Or might this introduce more problems?

Yeah I'm thinking this might cause issues depending on what variables work at this point yet etc. For example the siteId might only come from a variable etc and then things might not work correctly.
