### ISSUE TITLE
Using special characters in variable name results in errors in trigger configuration

### ISSUE THREAD

**Issue by Starker3** [matomo-org/tag-manager#308]
Currently it seems when creating a variable it's possible to use a `/` or `&` in the variable name. Doing so however results in the following error when creating a trigger using that variable (For example): 
`Conditions: The variable "URL Variable with / and &" in the condition at position "0" cannot be found.`

![image](https://user-images.githubusercontent.com/20905821/112061027-c6ca6000-8bc2-11eb-8961-adc46430d1f9.png)

![image](https://user-images.githubusercontent.com/20905821/112060929-af8b7280-8bc2-11eb-8931-0cc8ab8ff899.png)

We should either prevent users from being able to add special characters to variable names or sanitize the variable name to prevent issues like this.

**Comment by Starker3** [comment]
An easy fix for now would be to simply add a warning to the description saying something like:
"Only use numbers, letters and spaces for a variable name, using special characters will result in errors when using the variable"

**Comment by flamisz** [comment]
I investigated a little bit, what is the root cause of this issue. For me, the `/` character was not a problem, only the `&`. I checked it and when we save it to the DB we save it like `&amp;` so we can't find it when we search it. 
I'll look into it how to save and search in the same way.

**Comment by flamisz** [comment]
@tsteur I've found the root cause of the issue, see my comment above.

an easy fix can be, to `encodeURIComponent(this.variable.name)` before we post the `name` to the backend, and on the backend we `urldecode(name)` before we save it to the DB. this way we don't need the new validation.

are you happy with this solution? I can modify the #317 PR than

**Comment by tsteur** [comment]
sounds good 👍

**Comment by SW-Vincent** [comment]
Hi, I had a similar issue recently.

The "&" character was in the configuration variable name so there wasn't any kind of error message within the interface nor in dev console : all tracking just stopped.

This is a bit concerning, since there is not any form of error handling that would indicate to the user where does the problem come from.

Is there any fix planned for Cloud users ?
