### ISSUE TITLE
Users with "view" permissions have access to the Tag Manager

### ISSUE THREAD

**Issue by Jaimeapo** [matomo-org/tag-manager#329]
Users with "view" permissions have access to the Tag Manager, something that was not possible in previous versions 3.13.6.
Is there any intention of this to be the case as of version 4.1.1.?

Fortunately, it is not possible to make changes, but an error message appears "Your session has expired due to inactivity. Please log in to continue." But it goes back, in the browser, you can continue browsing ... (your session has not expired actually)
Which is also inconsistent, as something like "you are not allowed to make changes" should appear.

**Comment by diosmosis** [comment]
Hi @Jaimeapo, this appears to be intentional and was added in https://github.com/matomo-org/tag-manager/pull/73. Users w/ view permissions should only be able to view the information, they should not even be able to see icons required to go into edit mode. Is this not the case for you? If not, can you provide some screenshots to show us what you see (for example, the manage containers page w/ the icons accessible and the error message you see and where it occurs)?

**Comment by tsteur** [comment]
@Jaimeapo as @diosmosis it is indeed intentional that the configurations can be viewed but not edited. You should however not see any message like "Your session has expired". I've just tried to reproduce this using the latest version of Matomo and couldn't. I'll close this issue for now but if you still have this issue please comment with steps to reproduce this and we'll reopen again and have a look into it. Thanks for this.
