### ISSUE TITLE
Events apprear in Visitors Log only with "?mtm_preview_mode= container_ID" How to activate tags & triggers without it?

### ISSUE THREAD

**Issue by Mazino888** [matomo-org/tag-manager#385]
Hi all. Since I am new in analytics I would like to kindly ask a question in regard to Matomo Tag Manager. I have set up some tags and triggers, which do not activate in the preview mode. It is ONLY in preview mode that I am able to see on the Visitors Log the events of my actions. However, I tried to check if I could see those events without the preview mode, but it does not work unless I place at the end of the URLs interested page the partial link of matomo (?mtm_preview_mode= container ID).  How can I activate the tags and triggers without using the preview mode link? Thank you for your answers.

**Comment by Starker3** [comment]
Hi @Mazino888 
It sounds like you've not yet published the changes you've made to the "Live" version of your Matomo Container.
When using the Preview mode, you will automatically see the "Draft" version of your container.

You can find more information on publishing a container and all the changes you've made in our documentation: https://matomo.org/docs/tag-manager/#publish

**Comment by Mazino888** [comment]
Hi @Starker3. Thanks for your reply. I just published the tags & triggers however still the same stituation. After disabling the preview mode, I published the newst version. What could be the problem? Would be gratefull for some help. Thank you all :)

**Comment by Mazino888** [comment]
Recently I created 3 containers which are empty with the tracking code is installed in the CMS I use. Do I maybe have to copy-paste the tracking of the main container to the new ones? Might this be the issue?

**Comment by Starker3** [comment]
@Mazino888 You would need to make sure that the container you're publishing the changes to is the same container that is setup on your websites. If you're using different containers for different sites, then you'll need to make the necessary changes in each of the containers and then publish each of those containers.

I'd recommend creating a forum post to get some further help from the community: https://forum.matomo.org/
(Since asking questions like this through a GitHub issue is not the best method to get help)

**Comment by Mazino888** [comment]
Thank you for your help and advice. Appreciate it :)
