### ISSUE TITLE
Add support for `data-matomo-mask` attribute on events

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#503]
Currently the data-matomo-mask works for the heatmap and session recording but it does not work when it comes to events.
The typical use case is the following one, if you set the tracking of your events on any clicks happening on your website, then, a user may click on a personal data (for example his login while logged), as a result, the {{click text}} information may be sent to Matomo.
It would be useful to set the data-matomo-mask in order to not have the {{click text}} information sent to Matomo.

**Comment by sgiehl** [comment]
Hi @Chardonneaur 
Thanks for creating this suggestion. I'm actually not sure if that is an issue for core. The core features only allow to send events using a method, that allows passing custom data. The normal tracking won't fetch any data from certain elements and thus doesn't know where it might come from.
But I would assume this could possibly be something that might be considered for tag manager only. So that triggers that are fired might not use the elements content (or title, value,... ) if the `data-matomo-mask` attribute is set.
Or maybe try to explain that a bit more detailed if I got that wrong...

**Comment by Chardonneaur** [comment]
Thank you @sgiehl, yes, you got it right, I was also hesitating between putting it here or put it on the tag manager repository.
Can you move it to Tag Manager or should I create another issue on the tag manager repository?

**Comment by AltamashShaikh** [comment]
@Chardonneaur Thanks for creating the issue, our product team will review and add this to planned issues accordingly.
Meanwhile you can use a Custom JS variable to mask this, something like this
![Screenshot from 2022-06-29 09-18-34](https://user-images.githubusercontent.com/14902277/176347790-838949c6-1489-4683-9eb6-7a0e54ad5280.png)

**Comment by Chardonneaur** [comment]
@AltamashShaikh whao extra, thank you.

**Comment by heurteph-ei** [comment]
@AltamashShaikh, it could be a good idea, to put this sample of code in the Matomo FAQ during the time of implementation of this enhancement...

**Comment by AltamashShaikh** [comment]
@heurteph-ei Sure

For others above code if in case anyone needs it
```function () { 
var node = TagManager.dataLayer.get('mtm.clickElement');
 if(node && node.hasAttribute('data-matomo-mask')){
 	return '*******';
 }

 return node && node.text ? node.text : '';
}
```

**Comment by tsteur** [comment]
fyi from a privacy / compliance point of view our variables should support this directly though. Because as a website owner you want to ensure compliance. But you can never know what variables developers or marketers use and they could track personal data at any time thus even if there's above workaround, you can't guarantee that people use this.

So the only way for a website owner to guarantee this is to look at the site and check where personal data is being displayed and then set the `data-matomo-mask` attribute. This way you can ensure compliance and don't need to worry that someone might ever use click text variable etc.

The great thing is that the same will then also work for Heatmaps and Session Recordings.
