### ISSUE TITLE
Event value tracked on Tag Manager event doesn't work

### ISSUE THREAD

**Issue by nicointerstis** [matomo-org/tag-manager#692]
I'm trying to track workspace name at its creation using Tag manager containers On premise.

I'm using a custom var on the container that get the value of my DOM element. 
On the event tag request I got the good value for the e_v parameter (cf screenshot)
![image](https://github.com/matomo-org/tag-manager/assets/93703817/ecbffdaf-e77f-4e31-80d5-9d7a06dd84c1)

But on my report the event value is always "0" (cf screenshot) 
![image](https://github.com/matomo-org/tag-manager/assets/93703817/b892f34c-7c20-4b81-b3d9-224e55d0cc94)

Is that a bug ?

**Comment by snake14** [comment]
Hi @nicointerstis . Could you please provide some more information? What version of Matomo are you using? What does your custom variable configuration look like? Have you tried outputting just `e_v` by itself instead of concatenating with other values?

**Comment by nicointerstis** [comment]
Hi, thanks for reply. 

I'm using Matomo On-premise 4.15.1. 

The event tracking is set up on Tag manager on a button click. The event value should be populate by the text content value of a DOM elem. 

This is my tag 
![image](https://github.com/matomo-org/tag-manager/assets/93703817/3b7a6965-2f84-4232-a6ed-96b16939a963)

And this is my custom perimetre_nom variable 
![image](https://github.com/matomo-org/tag-manager/assets/93703817/baddfc07-107f-4449-b6ba-8e48227a731b)

I think this is working well cause the request has the good value. but on my Matomo Dashboard it is not populated

**Comment by snake14** [comment]
Thank you for the extra information @nicointerstis . I was able to reproduce the issue. I had forgotten that the event value is expected to be a number. If you try to enter a manual value instead of a variable, you get an error message stating that the value must be a number. I tested using a variable that returns a numeric value and it displays as expected in the visitor log:
![image](https://github.com/matomo-org/tag-manager/assets/11394099/1dc1fb06-a326-4102-9266-418639a54c0c)

So, `e_v` needs to be a numeric value to be displayed as the event value in Matomo. Sorry it's not more clear in Matomo Tag Manager, but [the API reference](https://developer.matomo.org/api-reference/tracking-api#optional-event-trackinghttpsmatomoorgdocsevent-tracking-info) mentions that `e_v` must be a float or integer. If you want it to display a non-numeric value, you will have to include it as part of the category, action, or name. I'm going to close this issue now, but please let me know if you think it should be re-opened for any reason.

**Comment by nicointerstis** [comment]
Yep I finally understand then. I will find another solution than event value :)

Thanks a lot for your time, you can close it.
