### ISSUE TITLE
Ability to export / search the tag lookup table (Manage Tags)

### ISSUE THREAD

**Issue by rcontiuk** [matomo-org/tag-manager#754]
Sites with a long list of tags (50+) are hard to manage, especially to find a specific tag. It would be useful to have a feature similar to **Behaviour / Pages** download and filter for tags:

![image](https://github.com/matomo-org/matomo/assets/49957970/5d77d80a-d509-4c07-8daf-aaa67a524899)

![Screenshot 2024-02-09 at 13 15 36](https://github.com/matomo-org/matomo/assets/49957970/da8cd75f-1373-43b2-9a44-efb1fac5cca4)

Additionally, it would be extremely helpful to be able to export / find not only the information visible in the tag lookup table, but also all the tag configuration, for instance the custom HTML code. So, instead of exporting/showing this:

![image](https://github.com/matomo-org/matomo/assets/49957970/55bd4fa1-db69-4b5d-89c1-f47357bb45db)

It would export/show all the tag configuration, showing all items:

![image](https://github.com/matomo-org/matomo/assets/49957970/4a9bdbde-e532-491b-92bb-f972d39220a3)

This would help users to quickly find the tag. Today, users have to open all tags to search the info and it takes a long time.

**Comment by AltamashShaikh** [comment]
In my opinion, the customer's should name the tags or add a description which gives them an idea what that tag does and would solve the problem of opening each tag.

**Comment by rcontiuk** [comment]
There are some scenarios, for example having an international team with many contributors adding tags, that increases the level of complexity in terms of managing tags. There are cases where some users inadvertently undo previous changes. Also, it is hard to find a particular code in a custom HTML tag. It would be very useful for example to type "event" to filter out all event tags.

**Comment by AltamashShaikh** [comment]
@rcontiuk Sure :+1: , we have marked the issue for prioritisation for the product team to have a look and schedule this accordingly.

**Comment by Stan-vw** [comment]
@rcontiuk thanks for making this ticket. Just to check if I understand the problem (putting aside the solution for the moment) - the problem is that when an instance has many tags, it's not easy to quickly find a specific tag.

This problem originates from a combination of things, including (but not limited to)
1. using a scalable naming framework for tags is probably not easy (since it requires significant thinking beforehand, and consistency of multiple users)
2. various fields are not readable without clicking into each specific tag
3. the display format isn't helpful when needing to read many names/fields (i.e. an export in excel is easy to read)
4. there is no search function to find the right tag (except for ctrl+F but that only searches on the tag names)

Does that sum up the problem?

**Comment by AltamashShaikh** [comment]
Implemented tag search, below video shows, what all advance search actions can be performed.

https://github.com/user-attachments/assets/1a9193a2-fd09-4a34-a554-ac3651d33145

**Comment by Stan-vw** [comment]
Thanks @AltamashShaikh 
@rcontiuk we'll ship the UX as seen in the video above, and wait to see if customers still require an export functionality after this. I imagine that a large portion of people that would've asked for an export will be helped sufficiently by the search functionality.
Note that we tried to add the same UX as in the datatables that are found across most reports, but since the tags/triggers/variables tables are not data tables we couldn't easily add that component, and had to find another UX that works.
