### ISSUE TITLE
Adding an easy way to create variables for HTML attributes

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#757]
Hi team,
Currently, we have a set of variables for the main HTML attributes like class, id, text.
But not for others, such as title, alt, custom HTML attributes.
It would be nice to have them as some source code are very rich and sometimes the data is within those attributes.
Thank you,

**Comment by AltamashShaikh** [comment]
@Chardonneaur Thanks for opening this issue, I have added this issue for prioritisation

**Comment by SW-Vincent** [comment]
Hi,

Same "issue" here !

While we have the option to specify a custom attribute for "Pages variables" > "DOM element" type variables, there is no such a thing as "Click variables" > "Click element" type variable that would let you chose a custom HTML attributes !
It would be useful because "data-" attributes are used a lot for custom tagging.

![screencapture-bergerlevrault-matomo-cloud-index-php-2024-02-16-15_21_22](https://github.com/matomo-org/tag-manager/assets/118832007/39f331ed-0b42-47fb-94e0-12ed8600de6b)

Note that the same issue goes with not being able to use the same URL-specific variables (host name, query, etc) for a clicked element URL (href).

**Comment by Chardonneaur** [comment]
@AltamashShaikh a data attribute variable has been released for the cloud, but it won't work for attribute with an hyphen, for example it works for data-category but not for data-in-stock. In the same spirit, the condition selection for data-attribute consider that it is a numerical value, no possibility to select a regex condition for example.
@Stan-vw

**Comment by AltamashShaikh** [comment]
@Chardonneaur I just checked this doesn't work for hyphen as the case is changed in JS, data-test-new becomes testNew, will add a fix for this also to work as expected

**Comment by snake14** [comment]
@Chardonneaur The new variable type should be available with the next Matomo release.
