### ISSUE TITLE
The preview mode does not respect the advanced settings of the tag

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#801]
Hi team,

It appears that when we configure some advanced settings for a tag, for example:
execute it once in a lifetime or once every 24 hours, the preview mode is not respecting those rules.
Here is a video to understand better what is happening:

https://github.com/matomo-org/tag-manager/assets/28002238/b465b862-ebf8-4fba-96bc-dc71c61ef6b7

Expected behaviour would be that the preview mode respect those conditions, so to say the preview mode should not react to the associate tag for 24 hours or for a lifetime.

Enhancement:
Implement a new setting which allows the customer to toggle whether tags are always triggered in debug mode or whether they follow the advanced settings. It should be possible by editing the code in [this section](https://github.com/matomo-org/tag-manager/blob/9af820d3622739f1a6093a5a83f8c9da8c856203/javascripts/tagmanager.js#L1452).

**Comment by atom-box** [comment]
I had one user report this today.

**Comment by snake14** [comment]
@Chardonneaur It appears that this was a deliberate design choice for debugging. Here's [a snippet of the code](https://github.com/matomo-org/tag-manager/blob/9af820d3622739f1a6093a5a83f8c9da8c856203/javascripts/tagmanager.js#L1452) that I found:
```
if (this.fireLimit === Tag.FIRE_LIMIT_ONCE_24HOURS && !window.mtmPreviewWindow) {
                        // in preview/debug mode we make sure to execute it
```

**Comment by Chardonneaur** [comment]
@snake14 thank you, would it be possible to make it as an on/off option?

**Comment by snake14** [comment]
@Chardonneaur Sure. That looks possible. We'd just have to determine the best place to put such a setting in the UI. I went ahead and updated the description to reflect that enhancement.

**Comment by Stan-vw** [comment]
We had an internal conversation about places this could be added. We suggest to add it in the global settings, because this reduces implementation time as well as solves a few UX issues compared to doing it on a container level.

The scope is to add a global setting dropdown/toggle that allows the user to set the method of MTM’s preview mode to one of the following:
- refreshing page resets the MTM triggers
- refreshing page does not reset the MTM triggers

See mockup attached
![image](https://github.com/user-attachments/assets/d605124e-fe43-42ce-ab42-426664c46b19)

**Comment by AltamashShaikh** [comment]
@Chardonneaur Added a new option in the container to respect the fire limits in preview mode when enabled and should be fixed with next core release
