### ISSUE TITLE
Automatically track the main events by generating a container for dummy users

### ISSUE THREAD

**Issue by Chardonneaur** [matomo-org/tag-manager#805]
Hi team,

Beginner Matomo users may be interested in having a container automatically created such as GA4 which would measure basic events such as clicks and scrolls.
This should be another option available in terms of tracking code when adding a website for the first time.

**Comment by Stan-vw** [comment]
Thanks for creating this ticket. It's worth noting that since some time last year, a container is automatically created when a measurable is added. In this container, the Matomo Analytics tag+variable is automatically configured, so using the out of the box MTM code is equally powerful as the JS code (plus benefits of easy extensability, changing things without needing a developer, version control etc).

I think that covers your suggestion, but feel free to reopen the ticket if something is missing
