### ISSUE TITLE
Automatically select container when only one is available

### ISSUE THREAD

**Issue by rcontiuk** [matomo-org/tag-manager#905]
Matomo doesn't automatically select the only available container for a particular website, users still have to select it manually:

![image](https://github.com/user-attachments/assets/3297d063-06c5-48fd-87fe-e65188553e34)

Ideally, the single container should be open automatically like this:

![image](https://github.com/user-attachments/assets/76e50472-184e-483e-b034-5f7c51590e29)

**Comment by AltamashShaikh** [comment]
@rcontiuk This looks like a good improvement :+1:

**Comment by snake14** [comment]
@rcontiuk I just tested in my local environment and when I switch to a site that only has one container and then open tag manager from the top navigation, it automatically selects the correct container. Can you please provide the exact flow that you're looking for? Also, which version of MTM are you testing with, since we've removed the Getting Started section in the latest version?

**Comment by rcontiuk** [comment]
@snake14 it looks like Matomo (OP and Cloud) opens the container **for the selected site ID** but when selecting a different site, it shows the "Manage Containers" menu instead. Like this:

![image](https://github.com/user-attachments/assets/5ef86acd-df8d-4b60-aba0-99bfe5638676)

Or this:

![image](https://github.com/user-attachments/assets/67a70f16-8119-4120-be7d-195aee3dbdbf)

Ideally we should make sure Matomo will select all single containers every time.

**Comment by snake14** [comment]
@rcontiuk We may need to have Product review the UX. However, if I understand correctly, it's behaving the way I'd expect. If I were viewing the list of available containers for one site and then selected a different site, I'd expect to see the list of containers for the newly selected site and not get redirected to the dashboard. If there were always an automatic redirect, there would be no way for customers to manage containers, such as adding/editing/deleting containers.

**Comment by rcontiuk** [comment]
@snake14 please refer to the video below that, hopefully, will clarify the misunderstanding. When selecting a site using the MTM dropdown menu, if there is only **one** container, it should automatically select it:

https://github.com/user-attachments/assets/8220657a-3f8e-404c-bf17-b330d39cfb41

This feature will enhance usability, particularly given that there are many instances with hundreds of sites.

**Comment by Stan-vw** [comment]
There's adjustments to this in the latest build. I see you still see "Getting started" so you're not on that version yet.
In the latest version, the container will be automatically selected when there is only 1 container, except when you are specifically on the Manage Containers screen and change website (since the user has shown to be interested to be on that screen).
In most cases, users will no longer see the Manage Containers screen 👍
